



<!DOCTYPE HTML>
<html lang=en>
<head>
<title>Log of /suikawiki/script/Makefile.PL &mdash; pub &mdash; Suika CVS Server</title>
<meta name="generator" content="ViewVC 1.1.5" />
<link rel="stylesheet" href="/gate/viewvc/statics/styles.css" type="text/css" />

<link rel=author href="/admin/cvs/" title="Suika CVS Server">
</head>
<body>
<div class="vc_navheader">
<table><tr>
<td><strong><a href="/gate/cvs/melon"><span class="pathdiv">/</span></a><a href="/gate/cvs/melon/pub/">[pub]</a><span class="pathdiv">/</span><a href="/gate/cvs/melon/pub/suikawiki/">suikawiki</a><span class="pathdiv">/</span><a href="/gate/cvs/melon/pub/suikawiki/script/">script</a><span class="pathdiv">/</span>Makefile.PL</strong></td>
<td style="text-align: right;"></td>
</tr></table>
</div>
<div style="float: right; padding: 5px;"><a href="http://suika.fam.cx/admin/cvs/" title="Suika CVS Server"><img src="http://suika.fam.cx/admin/logo/suikalogo" alt="Suika" width="200" height="70" /></a></div>
<h1>Log of /suikawiki/script/Makefile.PL</h1>

<p style="margin:0;">

<a href="/gate/cvs/melon/pub/suikawiki/script/"><img src="/gate/viewvc/statics/images/back_small.png" class="vc_icon" alt="Parent Directory" /> Parent Directory</a>

| <a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?view=log"><img src="/gate/viewvc/statics/images/log.png" class="vc_icon" alt="Revision Log" /> Revision Log</a>


| <a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?view=graph"><img src="/gate/viewvc/statics/images/cvsgraph_16x16.png" class="vc_icon" alt="View Revision Graph" /> Revision Graph</a>



</p>

<hr />
<table class="auto">



<tr>
<td>Links to HEAD:</td>
<td>
(<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?view=markup">view</a>)
(<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?view=co">download</a>)
(<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?content-type=text%2Fplain&amp;view=co">as text</a>)
(<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?view=annotate">annotate</a>)
</td>
</tr>



<tr>
<td>Sticky Tag:</td>
<td><form method="get" action="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL" style="display: inline">
<div style="display: inline">
<input type="hidden" name="view" value="log"/>


<select name="pathrev" onchange="submit()">
<option value=""></option>

<optgroup label="Branches">


<option>paragraph-200404</option>



<option>helowiki-melon-20091010</option>



<option>helowiki-2005</option>



<option>helowiki</option>



<option>MAIN</option>


</optgroup>

<optgroup label="Non-branch tags">


<option>suikawiki3-redirect</option>



<option>release-3-0-0</option>



<option>HEAD</option>


</optgroup>

</select>

<input type="submit" value="Set" />
</div>
</form>

</td>
</tr>
</table>
 







<div>
<hr />

<a name="rev1.3"></a>
<a name="suikawiki3-redirect"></a>
<a name="release-3-0-0"></a>
<a name="HEAD"></a>


Revision <strong>1.3</strong> -


(<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?revision=1.3&amp;view=markup">view</a>)


(<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?revision=1.3&amp;view=co">download</a>)
(<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?revision=1.3&amp;content-type=text%2Fplain&amp;view=co">as text</a>)
(<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?annotate=1.3">annotate</a>)



- <a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?r1=1.3&amp;view=log">[select for diffs]</a>




<br />

<em>Thu Mar 11 08:06:26 2004 UTC</em>
(6 years, 2 months ago)
by <em>wakaba</em>


<br />Branch:

<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?view=log&amp;pathrev=MAIN"><strong>MAIN</strong></a>



<br />CVS Tags:

<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?view=log&amp;pathrev=HEAD"><strong>HEAD</strong></a>,

<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?view=log&amp;pathrev=release-3-0-0"><strong>release-3-0-0</strong></a>,

<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?view=log&amp;pathrev=suikawiki3-redirect"><strong>suikawiki3-redirect</strong></a>



<br />Branch point for:

<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?view=log&amp;pathrev=helowiki"><strong>helowiki</strong></a>,

<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?view=log&amp;pathrev=helowiki-2005"><strong>helowiki-2005</strong></a>,

<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?view=log&amp;pathrev=helowiki-melon-20091010"><strong>helowiki-melon-20091010</strong></a>,

<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?view=log&amp;pathrev=paragraph-200404"><strong>paragraph-200404</strong></a>





<br />Changes since <strong>1.2: +6 -8 lines</strong>








<br />Diff to <a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?r1=1.2&amp;r2=1.3">previous 1.2</a>










<pre class="vc_log">*** empty log message ***
</pre>
</div>



<div>
<hr />

<a name="rev1.2"></a>


Revision <strong>1.2</strong> -


(<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?revision=1.2&amp;view=markup">view</a>)


(<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?revision=1.2&amp;view=co">download</a>)
(<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?revision=1.2&amp;content-type=text%2Fplain&amp;view=co">as text</a>)
(<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?annotate=1.2">annotate</a>)



- <a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?r1=1.2&amp;view=log">[select for diffs]</a>




<br />

<em>Sun Feb  1 12:40:51 2004 UTC</em>
(6 years, 4 months ago)
by <em>wakaba</em>


<br />Branch:

<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?view=log&amp;pathrev=MAIN"><strong>MAIN</strong></a>







<br />Changes since <strong>1.1: +12 -4 lines</strong>








<br />Diff to <a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?r1=1.1&amp;r2=1.2">previous 1.1</a>










<pre class="vc_log">Updated
</pre>
</div>



<div>
<hr />

<a name="rev1.1"></a>


Revision <strong>1.1</strong> -


(<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?revision=1.1&amp;view=markup">view</a>)


(<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?revision=1.1&amp;view=co">download</a>)
(<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?revision=1.1&amp;content-type=text%2Fplain&amp;view=co">as text</a>)
(<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?annotate=1.1">annotate</a>)



- <a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?r1=1.1&amp;view=log">[select for diffs]</a>




<br />

<em>Thu Dec  4 06:01:02 2003 UTC</em>
(6 years, 6 months ago)
by <em>wakaba</em>


<br />Branch:

<a href="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL?view=log&amp;pathrev=MAIN"><strong>MAIN</strong></a>

















<pre class="vc_log">New files
</pre>
</div>

 


 <hr />
<p><a name="diff"></a>
This form allows you to request diffs between any two revisions of this file.
For each of the two "sides" of the diff,

select a symbolic revision name using the selection box, or choose
'Use Text Field' and enter a numeric revision.

</p>
<form method="get" action="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL" id="diff_select">
<table cellpadding="2" cellspacing="0" class="auto">
<tr>
<td>&nbsp;</td>
<td>
<input type="hidden" name="view" value="diff"/>
Diffs between

<select name="r1">
<option value="text" selected="selected">Use Text Field</option>

<option value="1.3:suikawiki3-redirect">suikawiki3-redirect</option>

<option value="1.3:release-3-0-0">release-3-0-0</option>

<option value="1.3:paragraph-200404">paragraph-200404</option>

<option value="1.3:helowiki-melon-20091010">helowiki-melon-20091010</option>

<option value="1.3:helowiki-2005">helowiki-2005</option>

<option value="1.3:helowiki">helowiki</option>

<option value="1.3:MAIN">MAIN</option>

<option value="1.3:HEAD">HEAD</option>

</select>
<input type="text" size="12" name="tr1"
value="1.3"
onchange="document.getElementById('diff_select').r1.selectedIndex=0" />

and

<select name="r2">
<option value="text" selected="selected">Use Text Field</option>

<option value="1.3:suikawiki3-redirect">suikawiki3-redirect</option>

<option value="1.3:release-3-0-0">release-3-0-0</option>

<option value="1.3:paragraph-200404">paragraph-200404</option>

<option value="1.3:helowiki-melon-20091010">helowiki-melon-20091010</option>

<option value="1.3:helowiki-2005">helowiki-2005</option>

<option value="1.3:helowiki">helowiki</option>

<option value="1.3:MAIN">MAIN</option>

<option value="1.3:HEAD">HEAD</option>

</select>
<input type="text" size="12" name="tr2"
value="1.1"
onchange="document.getElementById('diff_select').r2.selectedIndex=0" />

</td>
</tr>
<tr>
<td>&nbsp;</td>
<td>
Type of Diff should be a
<select name="diff_format" onchange="submit()">
<option value="h" selected="selected">Colored Diff</option>
<option value="l" >Long Colored Diff</option>
<option value="f" >Full Colored Diff</option>
<option value="u" >Unidiff</option>
<option value="c" >Context Diff</option>
<option value="s" >Side by Side</option>
</select>
<input type="submit" value=" Get Diffs " />
</td>
</tr>
</table>
</form>



<form method="get" action="/gate/cvs/melon/pub/suikawiki/script/Makefile.PL">
<div>
<hr />
<a name="logsort"></a>
<input type="hidden" name="view" value="log"/>
Sort log by:
<select name="logsort" onchange="submit()">
<option value="cvs" >Not sorted</option>
<option value="date" selected="selected">Commit date</option>
<option value="rev" >Revision</option>
</select>
<input type="submit" value=" Sort " />
</div>
</form>


<hr />
<table>
<tr>
<td><address><a href="mailto:cvs@suika.fam.cx">cvs@suika.fam.cx</a></address></td>
<td style="text-align: right;"><strong><a href="/gate/viewvc/statics/help_log.html">ViewVC Help</a></strong></td>
</tr>
<tr>
<td>Powered by <a href="http://viewvc.tigris.org/">ViewVC 1.1.5</a></td>
<td style="text-align: right;">&nbsp;</td>
</tr>
</table>
</body>
</html>


