<!doctype html public "-//W3C//DTD HTML 4.0 Transitional//EN"
"http://www.w3.org/TR/REC-html40/loose.dtd">
<html><head>
<!-- ViewCVS -- http://viewcvs.sourceforge.net/
by Greg Stein -- mailto:gstein@lyra.org
-->
<title>CVS log for messaging/manakai/lib/Message/Makefile</title>
</head>
<body text="#000000" bgcolor="#ffffff">
<table width="100%" border=0 cellspacing=0 cellpadding=0>
<tr>
<td rowspan=2><h1>CVS log for messaging/manakai/lib/Message/Makefile</h1></td>
<td align=right><img src="/icons/apache_pb.gif" alt="(logo)" border=0
width=259 height=32></td>
</tr>
<tr>
<td align=right><h3><b><a
href="/gate/cvs/*docroot*/help_log.html">Help</a></b></h3></td>
</tr>
</table>
<a href="/gate/cvs/messaging/manakai/lib/Message/#Makefile"><img src="/icons/small/back.gif" alt="(back)" border=0
width=16 height=16></a>
<b>Up to <a href="/gate/cvs/#dirlist">[Suika]</a> / <a href="/gate/cvs/messaging/#dirlist">messaging</a> / <a href="/gate/cvs/messaging/manakai/#dirlist">manakai</a> / <a href="/gate/cvs/messaging/manakai/lib/#dirlist">lib</a> / <a href="/gate/cvs/messaging/manakai/lib/Message/#dirlist">Message</a></b><p>
<a href="#diff">Request diff between arbitrary revisions</a>

/ <a href="Makefile?graph=1">Display revisions graphically</a>

<hr noshade>

Default branch: MAIN
<br>
Bookmark a link to:

<a href="Makefile?rev=HEAD&content-type=text/vnd.viewcvs-markup"><b>HEAD</b></a>
/
(<a href="/gate/cvs/*checkout*/messaging/manakai/lib/Message/Makefile?rev=HEAD&content-type=text/plain"
><b>download</b></a>)


<br>


<hr size=1 noshade>

<a name="rev1.8"></a>
<a name="manakai-release-0-4-0"></a>
<a name="HEAD"></a>

<a name="MAIN"></a>

Revision

<a href="/gate/cvs/*checkout*/messaging/manakai/lib/Message/Makefile?rev=1.8"
><b>1.8</b></a>




/
<a href="Makefile?rev=1.8&content-type=text/vnd.viewcvs-markup"><b>(view)</b></a>


- <a href="Makefile?annotate=1.8">annotate</a>


- <a href="Makefile?r1=1.8">[select for diffs]</a>



, <i>Sat Aug 11 13:37:09 2007 UTC</i> (2 years, 9 months ago) by <i>wakaba</i>

<br>Branch:

<a href="Makefile?only_with_tag=MAIN"><b>MAIN</b></a>



<br>CVS Tags:

<a href="Makefile?only_with_tag=manakai-release-0-4-0"><b>manakai-release-0-4-0</b></a>,

<a href="Makefile?only_with_tag=HEAD"><b>HEAD</b></a>





<br>Changes since <b>1.7: +4 -10 lines</b>




<br>Diff to <a href="Makefile.diff?r1=1.7&r2=1.8">previous 1.7</a>







<pre>++ manakai/lib/Message/ChangeLog	11 Aug 2007 13:36:49 -0000
2007-08-11  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Makefile: New directory |CGI| is added.

2007-08-11  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* CGI/: New directory.

++ manakai/lib/Message/CGI/ChangeLog	11 Aug 2007 13:33:26 -0000
	* Makefile: New file.

	* HTTP.pm: Reformed for manakai.

2007-08-11  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;
</pre>

<hr size=1 noshade>

<a name="rev1.7"></a>


Revision

<a href="/gate/cvs/*checkout*/messaging/manakai/lib/Message/Makefile?rev=1.7"
><b>1.7</b></a>




/
<a href="Makefile?rev=1.7&content-type=text/vnd.viewcvs-markup"><b>(view)</b></a>


- <a href="Makefile?annotate=1.7">annotate</a>


- <a href="Makefile?r1=1.7">[select for diffs]</a>



, <i>Sun Jul 29 08:04:40 2007 UTC</i> (2 years, 10 months ago) by <i>wakaba</i>

<br>Branch:

<a href="Makefile?only_with_tag=MAIN"><b>MAIN</b></a>






<br>Changes since <b>1.6: +2 -6 lines</b>




<br>Diff to <a href="Makefile.diff?r1=1.6&r2=1.7">previous 1.6</a>







<pre>++ ChangeLog	29 Jul 2007 08:02:27 -0000
2007-07-29  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Makefile.PL: Updated.

++ manakai/lib/ChangeLog	29 Jul 2007 08:03:11 -0000
	* Makefile: No longer recurse into |manakai| and the
	AutoLoad module.

2007-07-29  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

++ manakai/lib/Message/ChangeLog	29 Jul 2007 08:03:25 -0000
2007-07-29  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Makefile (all): Special rule for |Util| is removed.

	* Charset/: Removed.

++ manakai/lib/Message/DOM/ChangeLog	29 Jul 2007 07:51:50 -0000
	* Text.pm: |Message::DOM::Traversal, an obsolete module,
	was referenced.

2007-07-29  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

++ manakai/lib/Message/Util/ChangeLog	29 Jul 2007 08:03:51 -0000
	* Makefile: Rules for DIS are removed.

2007-07-29  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

++ manakai/t/ChangeLog	29 Jul 2007 08:04:33 -0000
2007-07-29  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Makefile: Rules for DIS tests are removed.
</pre>

<hr size=1 noshade>

<a name="rev1.6"></a>
<a name="manakai-release-0-3-2"></a>
<a name="manakai-release-0-3-1"></a>
<a name="manakai-200612"></a>


Revision

<a href="/gate/cvs/*checkout*/messaging/manakai/lib/Message/Makefile?rev=1.6"
><b>1.6</b></a>




/
<a href="Makefile?rev=1.6&content-type=text/vnd.viewcvs-markup"><b>(view)</b></a>


- <a href="Makefile?annotate=1.6">annotate</a>


- <a href="Makefile?r1=1.6">[select for diffs]</a>



, <i>Fri Mar 31 16:44:23 2006 UTC</i> (4 years, 2 months ago) by <i>wakaba</i>

<br>Branch:

<a href="Makefile?only_with_tag=MAIN"><b>MAIN</b></a>



<br>CVS Tags:

<a href="Makefile?only_with_tag=manakai-release-0-3-2"><b>manakai-release-0-3-2</b></a>,

<a href="Makefile?only_with_tag=manakai-release-0-3-1"><b>manakai-release-0-3-1</b></a>,

<a href="Makefile?only_with_tag=manakai-200612"><b>manakai-200612</b></a>





<br>Changes since <b>1.5: +11 -1 lines</b>




<br>Diff to <a href="Makefile.diff?r1=1.5&r2=1.6">previous 1.5</a>







<pre>++ manakai/lib/Message/ChangeLog	31 Mar 2006 15:51:53 -0000
2006-03-31  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Makefile (clean-db): New rule.

++ manakai/lib/Message/Markup/ChangeLog	31 Mar 2006 15:53:04 -0000
2006-03-31  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Makefile (clean-db): New rule.

++ manakai/lib/Message/Util/ChangeLog	31 Mar 2006 15:59:50 -0000
	* Makefile (clean-db): New rule.

	* Grove.dis (onunload): New internal property.
	(collectGarbage): Invoke the |mg:onunload| code if available.

2006-03-31  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

++ manakai/lib/Message/DOM/ChangeLog	31 Mar 2006 15:58:33 -0000
2006-04-01  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* TreeCore.dis (setIdAttribute, setIdAttributeNS, setIdAttributeNode):
	Reimplemented.
	(isId): Setter is added.
	(Element.normalize): Definition copied from the |MDOM:Tree|
	module.

2006-03-31  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Makefile (clean-db): New rule.

	* TreeCore.dis (setUserData): Schedule to invoke
	the user data handler when the node is removed
	from the memory.
	(setAttribute, setAttributeNS): Set the [attribute type]
	if DTD attribute definition is available.
	(CharacterData members): Definitions copied from
	the |MDOM:Tree| module.

++ manakai/lib/Message/URI/ChangeLog	31 Mar 2006 15:54:48 -0000
2006-04-01  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Makefile (clean-db): New rule.

++ manakai/lib/Message/Charset/ChangeLog	31 Mar 2006 15:54:37 -0000
2006-04-01  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Makefile (clean-db): New rule.

++ manakai/lib/manakai/ChangeLog	31 Mar 2006 15:53:40 -0000
2006-03-31  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Makefile (clean-db): New rule.

++ manakai/lib/ChangeLog	31 Mar 2006 15:51:40 -0000
2006-03-31  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Makefile (clean-db): New rule.
</pre>

<hr size=1 noshade>

<a name="rev1.5"></a>


Revision

<a href="/gate/cvs/*checkout*/messaging/manakai/lib/Message/Makefile?rev=1.5"
><b>1.5</b></a>




/
<a href="Makefile?rev=1.5&content-type=text/vnd.viewcvs-markup"><b>(view)</b></a>


- <a href="Makefile?annotate=1.5">annotate</a>


- <a href="Makefile?r1=1.5">[select for diffs]</a>



, <i>Fri Mar 10 10:52:02 2006 UTC</i> (4 years, 2 months ago) by <i>wakaba</i>

<br>Branch:

<a href="Makefile?only_with_tag=MAIN"><b>MAIN</b></a>






<br>Changes since <b>1.4: +7 -1 lines</b>




<br>Diff to <a href="Makefile.diff?r1=1.4&r2=1.5">previous 1.4</a>







<pre>++ manakai/lib/Message/ChangeLog	10 Mar 2006 10:43:42 -0000
2006-03-10  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Makefile: Directories |URI| and |Charset| are added.

	* Charset/: New directory.

++ manakai/lib/Message/Util/ChangeLog	10 Mar 2006 10:51:06 -0000
2006-03-10  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* PerlCode.dis (stringify): Inserts new line after |COMMA|s
	in lists (hash literals and array literals --- "lists" theirselves
	are excluded since they are usually not so long).

	* DIS.dis (loadResource): Don't throw error
	if an alias is alreadt defined for same URI.  Registers
	aliases from |srinfo| to the database. By these
	fixes aliases defined in another module from the canonical
	resource name's module can live even after the canonical's
	module is updated.

++ manakai/lib/Message/DOM/ChangeLog	10 Mar 2006 10:44:35 -0000
2006-03-10  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* DOMCore.dis, DOMXML.dis, XDoctype.dis (manakaiAppendText): New
	method.

	* XMLParser.dis: Don't create adjacent text nodes.

++ manakai/lib/Message/URI/ChangeLog	10 Mar 2006 10:47:21 -0000
2006-03-10  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Generic.dis (MURI:): Typos are fixed.

++ manakai/lib/manakai/ChangeLog	10 Mar 2006 10:51:43 -0000
2006-03-10  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* dis-catalog: New |Message::Charset| namespace is added.
</pre>

<hr size=1 noshade>

<a name="rev1.4"></a>


Revision

<a href="/gate/cvs/*checkout*/messaging/manakai/lib/Message/Makefile?rev=1.4"
><b>1.4</b></a>




/
<a href="Makefile?rev=1.4&content-type=text/vnd.viewcvs-markup"><b>(view)</b></a>


- <a href="Makefile?annotate=1.4">annotate</a>


- <a href="Makefile?r1=1.4">[select for diffs]</a>



, <i>Sun Feb 26 14:32:38 2006 UTC</i> (4 years, 3 months ago) by <i>wakaba</i>

<br>Branch:

<a href="Makefile?only_with_tag=MAIN"><b>MAIN</b></a>






<br>Changes since <b>1.3: +13 -3 lines</b>




<br>Diff to <a href="Makefile.diff?r1=1.3&r2=1.4">previous 1.3</a>







<pre>++ manakai/t/ChangeLog	26 Feb 2006 14:32:29 -0000
	* Makefile (distclean): New rule.

2006-02-26  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

++ manakai/bin/ChangeLog	26 Feb 2006 14:18:44 -0000
	* daf.pl: Request for |fe:GenericLS| feature was missing.
	Sets the |pc:preserve-line-break| parameter for test
	code as |dac2test.pl| had been.

	* dac.pl, dac2pm.pl, dac2test.pl: Removed.

	* disc.pl, cdis2pm.pl, cdis2rdf.pl: Removed.

2006-02-26  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

++ manakai/lib/Message/ChangeLog	26 Feb 2006 14:19:17 -0000
2006-02-26  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Makefile (distclean): New rule.

++ manakai/lib/Message/Body/ChangeLog	26 Feb 2006 14:19:35 -0000
2006-02-26  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Makefile (distclean): New rule.

++ manakai/lib/Message/Field/ChangeLog	26 Feb 2006 14:24:08 -0000
2006-02-26  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Makefile (distclean): New rule.

++ manakai/lib/Message/MIME/ChangeLog	26 Feb 2006 14:24:31 -0000
2006-02-26  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Makefile (distclean): New rule.

++ manakai/lib/Message/Markup/ChangeLog	26 Feb 2006 14:24:49 -0000
	* Makefile (distclean): New rule.

2006-02-26  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

++ manakai/lib/Message/Util/ChangeLog	26 Feb 2006 14:27:24 -0000
	* PerlCode.dis (PerlStringLiteral.stringify): If some character
	are escaped, the string should have been quoted by |QUOTATION MARK|.

	* Makefile (.discore-all.pm): The parameter for |DIS/DPG.dis|
	module was misplaced.
	(distclean): New rule.
	(clean): Cleans subdirectories, too.

2006-02-26  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

++ manakai/lib/Message/Util/DIS/ChangeLog	26 Feb 2006 14:31:14 -0000
	* Perl.dis (plUpdate): Reads |dis:DefaultFor| property
	from the source if it is not available from the module
	in the database, i.e. the |readProperties| method
	is not performed for the module.
	(getPerlInterfaceMemberCode): Renamed
	from |getPerlErrorInterfaceMemberCode|.
	(DISLang:Const.getPerlInterfaceMemberCode): New
	method implementation.  Constants defined in interfaces
	were not reflected to the generated Perl module code
	since the split of |plGeneratePerlModule| method.

	* DPG.dis (Require): Reference to |DIS:Perl| module was missing.

2006-02-26  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

++ manakai/lib/Message/DOM/ChangeLog	26 Feb 2006 14:21:51 -0000
	* SimpleLS.dis (Require): Reference to the |MDOM:Tree|
	module was missing.

	* ManakaiDOMLS2003.dis: Some property names was incorrect.

	* Makefile (distclean): New rule.

2006-02-26  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* DOMLS.dis: Removed from the CVS repository, since
	it has been no longer required to make the |daf| system
	itself.

2006-02-26  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

++ manakai/lib/manakai/ChangeLog	26 Feb 2006 14:32:09 -0000
	* Makefile (distclean): New rule.

2006-02-26  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

++ manakai/lib/ChangeLog	26 Feb 2006 14:19:00 -0000
2006-02-26  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Makefile (distclean): New rule.
</pre>

<hr size=1 noshade>

<a name="rev1.3"></a>


Revision

<a href="/gate/cvs/*checkout*/messaging/manakai/lib/Message/Makefile?rev=1.3"
><b>1.3</b></a>




/
<a href="Makefile?rev=1.3&content-type=text/vnd.viewcvs-markup"><b>(view)</b></a>


- <a href="Makefile?annotate=1.3">annotate</a>


- <a href="Makefile?r1=1.3">[select for diffs]</a>



, <i>Sat Sep 24 11:57:19 2005 UTC</i> (4 years, 8 months ago) by <i>wakaba</i>

<br>Branch:

<a href="Makefile?only_with_tag=MAIN"><b>MAIN</b></a>






<br>Changes since <b>1.2: +4 -2 lines</b>




<br>Diff to <a href="Makefile.diff?r1=1.2&r2=1.3">previous 1.2</a>







<pre>++ manakai/bin/ChangeLog	24 Sep 2005 10:49:30 -0000
	(dac_load_module_file): Allow "|" as qname prefix separator.
++ manakai/lib/Message/Markup/ChangeLog	24 Sep 2005 11:11:32 -0000
2005-09-24  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* SuikaWikiConfig21.dis: Use "disPerl:H" instead
	of "disPerl:Q" for hash keys.
	(expandQName): Removed the "g" option from the "s///",
	which was very serious and difficult bug.

++ manakai/lib/Message/Util/ChangeLog	24 Sep 2005 11:01:40 -0000
2005-09-24  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* ManakaiNode.dis (mn:node, mn:nodeID, mn:treeID): New
	properties.
	(mn:stemName, mn:refName): New properties.

	* Makefile (.discore-all.pm): New rule to create dis-related
	Perl module files at once.

	* DIS.dis (PERL_HASH_KEY_ALREADY_DEFINED_ERR): New error code.
	(hashKeyName, hashKeyScope, anotherURI): New error parameters.

	* ManakaiNode.dis, DIS.dis, PerlCode.dis: Use "disPerl:H" instead
	of "disPerl:Q" for hash keys.

++ manakai/lib/Message/Util/Error/ChangeLog	24 Sep 2005 10:58:31 -0000
2005-09-24  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* ManakaiNode.dis: Use "disPerl:H" instead
	of "disPerl:Q" for hash keys.

++ manakai/lib/Message/Util/DIS/ChangeLog	24 Sep 2005 11:06:19 -0000
2005-09-24  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Perl.dis (plCodeFragment): Takes hash key name
	from the database for "mn:node" and "DOMCore:read-only",
	where they were hardcoded.  For GetProp and SetProp
	dis tree element instructions, hash key name
	is shorten if shorter version is defined by "DISPerl:propHashKey"
	property of the corresponding resource in the database.
	(plAddHashKey): New method to check hash key name dupulication.
	(dp:plHashKey): New property.

	* Perl.dis, DNLite.dis, DISDoc.dis, DISDump.dis:
	Use "disPerl:H" instead of "disPerl:Q" for hash keys.

++ manakai/lib/Message/DOM/ChangeLog	24 Sep 2005 10:55:11 -0000
2005-09-24  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* DOMMain.dis (MDOM:): Reintroduced for "ManakaiDOM:ManakaiDOM1"
	and "ManakaiDOM:ManakaiDOM2".

	* DOMFeature.dis, DOMMain.dis, DOMCore.dis, DOMXML.dis,
	DOMLS.dis, SimpleLS.dis, GenericLS.dis: Use disPerl:H
	instead of disPerl:Q for internal property hash keys.

	* DOMFeature.dis, DOMCore.dis, DOMXML.dis: Missing property
	definitions added.

	* DOMCore.dis (DOMCore:TextNode, DOMCore:DocumentFragmentNode):
	New resources.

	* DOMXML.dis (DOMXML:EntityNode, DOMXML:EntityReferenceNode): New
	resources.

++ manakai/lib/manakai/ChangeLog	24 Sep 2005 11:08:14 -0000
2005-09-24  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* XML.dis: The "DISPerl:propHashKey" property
	added to properties.  Now the module depends on the DISPerl
	module.

	* DISPerl.dis (DISPerl:propHashKey): New property.
</pre>

<hr size=1 noshade>

<a name="rev1.2"></a>


Revision

<a href="/gate/cvs/*checkout*/messaging/manakai/lib/Message/Makefile?rev=1.2"
><b>1.2</b></a>




/
<a href="Makefile?rev=1.2&content-type=text/vnd.viewcvs-markup"><b>(view)</b></a>


- <a href="Makefile?annotate=1.2">annotate</a>


- <a href="Makefile?r1=1.2">[select for diffs]</a>



, <i>Thu Sep 22 14:25:46 2005 UTC</i> (4 years, 8 months ago) by <i>wakaba</i>

<br>Branch:

<a href="Makefile?only_with_tag=MAIN"><b>MAIN</b></a>






<br>Changes since <b>1.1: +16 -4 lines</b>




<br>Diff to <a href="Makefile.diff?r1=1.1&r2=1.2">previous 1.1</a>







<pre>++ manakai/lib/Message/ChangeLog	22 Sep 2005 12:48:57 -0000
2005-09-22  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Makefile: Rules to build subdirectories added.

++ manakai/lib/Message/Markup/ChangeLog	22 Sep 2005 12:52:49 -0000
2005-09-22  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Makefile: DAC_SUFFIX changed to ".dad".

++ manakai/lib/Message/Util/ChangeLog	22 Sep 2005 12:52:57 -0000
	* Makefile: DAC_SUFFIX changed to ".dad".

++ manakai/lib/Message/DOM/ChangeLog	22 Sep 2005 12:52:41 -0000
2005-09-22  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Makefile: DAC_SUFFIX changed to ".dad".

++ manakai/lib/manakai/ChangeLog	22 Sep 2005 12:53:54 -0000
2005-09-22  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Makefile: DAC_SUFFIX changed to ".dad".

++ manakai/lib/ChangeLog	22 Sep 2005 12:48:26 -0000
2005-09-22  Wakaba  &lt;<a href="mailto:wakaba@suika.fam.cx">wakaba@suika.fam.cx</a>&gt;

	* Makefile: Old "bootstrap" rules all removed.
</pre>

<hr size=1 noshade>

<a name="rev1.1"></a>
<a name="stable"></a>
<a name="msg-0-1"></a>
<a name="experimental-xml-parser-200401"></a>
<a name="branch-suikawiki-1"></a>
<a name="before-dis2-200411"></a>


Revision

<a href="/gate/cvs/*checkout*/messaging/manakai/lib/Message/Makefile?rev=1.1"
><b>1.1</b></a>




/
<a href="Makefile?rev=1.1&content-type=text/vnd.viewcvs-markup"><b>(view)</b></a>


- <a href="Makefile?annotate=1.1">annotate</a>


- <a href="Makefile?r1=1.1">[select for diffs]</a>



, <i>Sun May 26 01:20:10 2002 UTC</i> (8 years ago) by <i>wakaba</i>

<br>Branch:

<a href="Makefile?only_with_tag=MAIN"><b>MAIN</b></a>



<br>CVS Tags:

<a href="Makefile?only_with_tag=stable"><b>stable</b></a>,

<a href="Makefile?only_with_tag=msg-0-1"><b>msg-0-1</b></a>,

<a href="Makefile?only_with_tag=experimental-xml-parser-200401"><b>experimental-xml-parser-200401</b></a>,

<a href="Makefile?only_with_tag=branch-suikawiki-1"><b>branch-suikawiki-1</b></a>,

<a href="Makefile?only_with_tag=before-dis2-200411"><b>before-dis2-200411</b></a>










<pre>2002-05-26  wakaba &lt;<a href="mailto:w@suika.fam.cx">w@suika.fam.cx</a>&gt;

	* Header.pm (url_mailto_safe): Removed.
	(Moved to Message::Header::RFC822.)
	
	* Makefile: New file.
</pre>

<a name=diff></a>
<hr noshade>
This form allows you to request diffs between any two revisions of
a file. You may select a symbolic revision name using the selection
box or you may type in a numeric name using the type-in text box.
<p>
<form method="GET" action="Makefile.diff" name="diff_select">
Diffs between
<select name="r1">
<option value="text" selected>Use Text Field</option>

<option value="1.1.0.2:stable">stable</option>

<option value="1.1:msg-0-1">msg-0-1</option>

<option value="1.8:manakai-release-0-4-0">manakai-release-0-4-0</option>

<option value="1.6:manakai-release-0-3-2">manakai-release-0-3-2</option>

<option value="1.6:manakai-release-0-3-1">manakai-release-0-3-1</option>

<option value="1.6:manakai-200612">manakai-200612</option>

<option value="1.1.0.6:experimental-xml-parser-200401">experimental-xml-parser-200401</option>

<option value="1.1.0.4:branch-suikawiki-1">branch-suikawiki-1</option>

<option value="1.1:before-dis2-200411">before-dis2-200411</option>

<option value="0.1:MAIN">MAIN</option>

<option value="1.8:HEAD">HEAD</option>

</select>
<input type="TEXT" size="12" name="tr1" value="1.1"
onChange="document.diff_select.r1.selectedIndex=0">
and
<select name="r2">
<option value="text" selected>Use Text Field</option>

<option value="1.1.0.2:stable">stable</option>

<option value="1.1:msg-0-1">msg-0-1</option>

<option value="1.8:manakai-release-0-4-0">manakai-release-0-4-0</option>

<option value="1.6:manakai-release-0-3-2">manakai-release-0-3-2</option>

<option value="1.6:manakai-release-0-3-1">manakai-release-0-3-1</option>

<option value="1.6:manakai-200612">manakai-200612</option>

<option value="1.1.0.6:experimental-xml-parser-200401">experimental-xml-parser-200401</option>

<option value="1.1.0.4:branch-suikawiki-1">branch-suikawiki-1</option>

<option value="1.1:before-dis2-200411">before-dis2-200411</option>

<option value="0.1:MAIN">MAIN</option>

<option value="1.8:HEAD">HEAD</option>

</select>
<input type="TEXT" size="12" name="tr2" value="1.8"
onChange="document.diff_select.r1.selectedIndex=0">
<br>Type of Diff should be a
<select name="diff_format" onchange="submit()">
<option value="h" selected>Colored Diff</option>
<option value="l" >Long Colored Diff</option>
<option value="u" >Unidiff</option>
<option value="c" >Context Diff</option>
<option value="s" >Side by Side</option>
</select>
<input type=submit value=" Get Diffs "></form>
<hr noshade>

<a name=branch></a>
<form method="GET" action="Makefile">

View only Branch:
<select name="only_with_tag" onchange="submit()">
<option value="" selected>Show all branches</option>

<option value="stable" >stable</option>

<option value="experimental-xml-parser-200401" >experimental-xml-parser-200401</option>

<option value="branch-suikawiki-1" >branch-suikawiki-1</option>

<option value="MAIN" >MAIN</option>

</select>
<input type=submit value=" View Branch ">
</form>

<a name=logsort></a>
<form method="GET" action="Makefile">

Sort log by:
<select name="logsort" onchange="submit()">
<option value="cvs" >Not sorted</option>
<option value="date" selected>Commit date</option>
<option value="rev" >Revision</option>
</select>
<input type=submit value=" Sort ">
</form>

<div class="footer">
<p>&#x5B;<a href="/admin/cvs/">About Suika CVS Repositories</a>&#x5D;</p>
<address><a href="mailto:webmaster@suika.fam.cx">Webmaster</a></address>
<address lang="en">Powered by <a href="http://viewcvs.sourceforge.net/">ViewCVS 0.9.2</a></address>
</body></html>

